# DataSource Config
spring:
  datasource:
#    driver-class-name: com.mysql.cj.jdbc.Driver
#    url: jdbc:mysql://39.107.13.154:3306/wills_blog?useUnicode=true&useSSL=false&characterEncoding=utf8&serverTimezone=UTC
    driver-class-name: com.p6spy.engine.spy.P6SpyDriver
    url: jdbc:p6spy:mysql://39.107.13.154:3306/wills_blog?useUnicode=true&useSSL=false&characterEncoding=utf8&serverTimezone=UTC
    username: root
    password: 123456
  freemarker:
    settings:
      classic_compatible: true
      datetime_format: yyyy-MM-dd HH:mm
      number_format: 0.##
  redis:
    host: 39.107.13.154
    port: 6379
    password:
  data:
    elasticsearch:
      cluster-name: kobe
      cluster-nodes: 39.107.13.154:9300
      repositories:
        enabled: true
  rabbitmq:
    username: guest
    password: guest
    host: 39.107.13.154
    port: 5672